# general configuration
url: http://claman.github.io
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/compass.png"
  # author will appear under the avatar (optional)
  author: "Alex Claman"
  # tagline will appear under the title (optional)
  tagline: "My Github landing page"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false

# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty
